// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

public class Activation
{
    private Boolean activeByDefault = false;
    public final String jdk;
    public final ActivationOS os;
    public final ActivationProperty property;
    public final ActivationFile file;
    public final java.util.Map<Object, InputLocation> locations;

    public Activation( Boolean activeByDefault, String jdk, ActivationOS os, ActivationProperty property,
                       ActivationFile file, Map<Object, InputLocation> locations )
    {
        this.activeByDefault = activeByDefault;
        this.jdk = jdk;
        this.os = os;
        this.property = property;
        this.file = file;
        this.locations = locations;
    }
}
