// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * This is the file specification used to activate the profile. The
 * <code>missing</code> value
 *         is the location of a file that needs to exist, and if it
 * doesn't, the profile will be
 *         activated. On the other hand, <code>exists</code> will
 * test for the existence of the file and if it is
 *         there, the profile will be activated.<br/>
 *         Variable interpolation for these file specifications is
 * limited to <code>${basedir}</code>,
 *         System properties and request properties.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class ActivationFile
{
    private String missing;
    private String exists;
    private java.util.Map<Object, InputLocation> locations;

    public ActivationFile( String missing, String exists, Map<Object, InputLocation> locations )
    {
        this.missing = missing;
        this.exists = exists;
        this.locations = locations;
    }
}
