// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

public class ActivationOS
{
    public final String name;
    public final String family;
    public final String arch;
    public final String version;
    private java.util.Map<Object, InputLocation> locations;

    public ActivationOS( String name, String family, String arch, String version, Map<Object, InputLocation> locations )
    {
        this.name = name;
        this.family = family;
        this.arch = arch;
        this.version = version;
        this.locations = locations;
    }
}
