// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

public class ActivationProperty
{
    public final String name;
    public final String value;
    public final java.util.Map<Object, InputLocation> locations;

    public ActivationProperty( String name, String value, Map<Object, InputLocation> locations )
    {
        this.name = name;
        this.value = value;
        this.locations = locations;
    }
}
