// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * 
 *         
 *         The <code>&lt;build&gt;</code> element contains
 * informations required to build the project.
 *         
 *       
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Build
    extends BuildBase
{

    private String sourceDirectory;
    private String scriptSourceDirectory;
    private String testSourceDirectory;
    private String outputDirectory;
    private String testOutputDirectory;
    private java.util.List<Extension> extensions;

    public Build( List<Plugin> plugins, Map<Object, InputLocation> locations, PluginManagement pluginManagement,
                  String defaultGoal, List<Resource> resources, List<Resource> testResources, String directory,
                  String finalName, List<String> filters, String sourceDirectory, String scriptSourceDirectory,
                  String testSourceDirectory, String outputDirectory, String testOutputDirectory,
                  List<Extension> extensions )
    {
        super( plugins, locations, pluginManagement, defaultGoal, resources, testResources, directory, finalName,
               filters );
        this.sourceDirectory = sourceDirectory;
        this.scriptSourceDirectory = scriptSourceDirectory;
        this.testSourceDirectory = testSourceDirectory;
        this.outputDirectory = outputDirectory;
        this.testOutputDirectory = testOutputDirectory;
        this.extensions = extensions;
    }
}
