// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

public class BuildBase
    extends PluginConfiguration
{
    public final String defaultGoal;
    public final java.util.List<Resource> resources;
    public final java.util.List<Resource> testResources;
    public final String directory;
    public final String finalName;
    public final java.util.List<String> filters;

    public BuildBase( List<Plugin> plugins, Map<Object, InputLocation> locations, PluginManagement pluginManagement,
                      String defaultGoal, List<Resource> resources, List<Resource> testResources, String directory,
                      String finalName, List<String> filters )
    {
        super( plugins, locations, pluginManagement );
        this.defaultGoal = defaultGoal;
        this.resources = resources;
        this.testResources = testResources;
        this.directory = directory;
        this.finalName = finalName;
        this.filters = filters;
    }
}
