// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * 
 *         
 *         The <code>&lt;CiManagement&gt;</code> element contains
 * informations required to the
 *         continuous integration system of the project.
 *         
 *       
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class CiManagement
{
    private String system;
    private String url;
    private java.util.List<Notifier> notifiers;
    private java.util.Map<Object, InputLocation> locations;

    public CiManagement( String system, String url, List<Notifier> notifiers, Map<Object, InputLocation> locations )
    {
        this.system = system;
        this.url = url;
        this.notifiers = notifiers;
        this.locations = locations;
    }
}
