// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * Repository contains the information needed for deploying to the
 * remote
 *         repository.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class DeploymentRepository
    extends Repository
{

    private Boolean uniqueVersion = true;

    public DeploymentRepository( String id, String name, String url, String layout,
                                 Map<Object, InputLocation> locations, RepositoryPolicy releases,
                                 RepositoryPolicy snapshots, Boolean uniqueVersion )
    {
        super( id, name, url, layout, locations, releases, snapshots );
        this.uniqueVersion = uniqueVersion;
    }
}
