// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;
import java.util.Properties;

/**
 * Information about one of the committers on this project.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Developer
    extends Contributor
    implements java.io.Serializable
{

    public final String id;

    public Developer( int hashCode, String name, String email, String url, String organization, String organizationUrl,
                       List<String> roles, String timezone, Properties properties, Map<Object, InputLocation> locations,
                       String id )
    {
        super( hashCode, name, email, url, organization, organizationUrl, roles, timezone, properties, locations );
        this.id = id;
    }

    @Override
    public boolean equals( Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        if ( !super.equals( o ) )
        {
            return false;
        }

        Developer developer = (Developer) o;

        if ( id != null ? !id.equals( developer.id ) : developer.id != null )
        {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int result = super.hashCode();
        result = 31 * result + ( id != null ? id.hashCode() : 0 );
        return result;
    }


    public static int hashCode( String id, String name, String email, String url, String organization, String organizationUrl,
                                List<String> roles, String timezone, Properties properties )
    {

        int result = 0;
        result = 31 * result + ( id != null ? id.hashCode() : 0 );
        int hc =
            Contributor.hashCode( name, email, url, organization, organizationUrl, roles, timezone, properties );
        result = 31 * result +hc ;
        return result;
    }

}
