// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * This elements describes all that pertains to distribution for a
 * project. It is
 *         primarily used for deployment of artifacts and the site
 * produced by the build.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class DistributionManagement
{
    private DeploymentRepository repository;
    private DeploymentRepository snapshotRepository;
    private Site site;
    private String downloadUrl;
    private Relocation relocation;
    private String status;
    private java.util.Map<Object, InputLocation> locations;

    public DistributionManagement( DeploymentRepository repository, DeploymentRepository snapshotRepository, Site site,
                                   String downloadUrl, Relocation relocation, String status,
                                   Map<Object, InputLocation> locations )
    {
        this.repository = repository;
        this.snapshotRepository = snapshotRepository;
        this.site = site;
        this.downloadUrl = downloadUrl;
        this.relocation = relocation;
        this.status = status;
        this.locations = locations;
    }
}
