// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * 
 *         
 *         The <code>&lt;exclusion&gt;</code> element contains
 * informations required to exclude
 *         an artifact to the project.
 *         
 *       
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Exclusion
{
    private String artifactId;

    private String groupId;

    private java.util.Map<Object, InputLocation> locations;

    public Exclusion( String artifactId, String groupId, Map<Object, InputLocation> locations )
    {
        this.artifactId = artifactId;
        this.groupId = groupId;
        this.locations = locations;
    }

}
