// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * Describes a build extension to utilise.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Extension
{
    private String groupId;
    private String artifactId;
    private String version;
    private java.util.Map<Object, InputLocation> locations;

    public Extension( String groupId, String artifactId, String version, Map<Object, InputLocation> locations )
    {
        this.groupId = groupId;
        this.artifactId = artifactId;
        this.version = version;
        this.locations = locations;
    }
}
