// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * A PatternSet for files.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class FileSet
    extends PatternSet
{
    private String directory;


    public FileSet( List<String> includes, List<String> excludes, Map<Object, InputLocation> locations,
                    String directory )
    {
        super( includes, excludes, locations );
        this.directory = directory;
    }
}
