// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

public final class InputLocation
{
   private int lineNumber = -1;
    private int columnNumber = -1;
    private InputSource source;
    private java.util.Map<Object, InputLocation> locations;

    public InputLocation( int lineNumber, int columnNumber, InputSource source, Map<Object, InputLocation> locations )
    {
        this.lineNumber = lineNumber;
        this.columnNumber = columnNumber;
        this.source = source;
        this.locations = locations;
    }
}
