// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

public class InputSource
{

    public final String modelId;
    public final String location;

    public InputSource( String modelId, String location )
    {
        this.modelId = modelId;
        this.location = location;
    }
}
