// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * Information about the issue tracking (or bug tracking) system
 * used to manage this
 *         project.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class IssueManagement
{
    private String system;
    private String url;
    private java.util.Map<Object, InputLocation> locations;

    public IssueManagement( String system, String url, Map<Object, InputLocation> locations )
    {
        this.system = system;
        this.url = url;
        this.locations = locations;
    }
}
