// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * Describes the licenses for this project. This is used to
 * generate the license
 *         page of the project's web site, as well as being taken
 * into consideration in other reporting
 *         and validation. The licenses listed for the project are
 * that of the project itself, and not
 *         of dependencies.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class License
{
    private String name;
    private String url;
    private String distribution;
    private String comments;
    private java.util.Map<Object, InputLocation> locations;

    public License( String name, String url, String distribution, String comments,
                    Map<Object, InputLocation> locations )
    {
        this.name = name;
        this.url = url;
        this.distribution = distribution;
        this.comments = comments;
        this.locations = locations;
    }
}
