// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

public class MailingList
{

    private String name;
    private String subscribe;
    private String unsubscribe;
    private String post;
    private String archive;
    private java.util.List<String> otherArchives;
    private java.util.Map<Object, InputLocation> locations;

    public MailingList( String name, String subscribe, String unsubscribe, String post, String archive,
                        List<String> otherArchives, Map<Object, InputLocation> locations )
    {
        this.name = name;
        this.subscribe = subscribe;
        this.unsubscribe = unsubscribe;
        this.post = post;
        this.archive = archive;
        this.otherArchives = otherArchives;
        this.locations = locations;
    }
}
