// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;
import java.util.Properties;

/**
 * 
 *         
 *         Base class for the <code>Model</code> and the
 * <code>Profile</code> objects.
 *         
 *       
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class ModelBase
{
    private java.util.List<String> modules;
    private DistributionManagement distributionManagement;
    private java.util.Properties properties;
    private DependencyManagement dependencyManagement;
    private java.util.List<Dependency> dependencies;
    private java.util.List<Repository> repositories;
    private java.util.List<Repository> pluginRepositories;
    private Object reports;
    private Reporting reporting;
    private java.util.Map<Object, InputLocation> locations;

    public ModelBase( List<String> modules, DistributionManagement distributionManagement, Properties properties,
                      DependencyManagement dependencyManagement, List<Dependency> dependencies,
                      List<Repository> repositories, List<Repository> pluginRepositories, Object reports,
                      Reporting reporting, Map<Object, InputLocation> locations )
    {
        this.modules = modules;
        this.distributionManagement = distributionManagement;
        this.properties = properties;
        this.dependencyManagement = dependencyManagement;
        this.dependencies = dependencies;
        this.repositories = repositories;
        this.pluginRepositories = pluginRepositories;
        this.reports = reports;
        this.reporting = reporting;
        this.locations = locations;
    }
}
