// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;
import java.util.Properties;

public class Notifier
{

    private String type = "mail";
    private Boolean sendOnError = true;
    private Boolean sendOnFailure = true;
    private Boolean sendOnSuccess = true;
    private Boolean sendOnWarning = true;
    private String address;
    private java.util.Properties configuration;
    private java.util.Map<Object, InputLocation> locations;

    public Notifier( String type, Boolean sendOnError, Boolean sendOnFailure, Boolean sendOnSuccess,
                     Boolean sendOnWarning, String address, Properties configuration,
                     Map<Object, InputLocation> locations )
    {
        this.type = type;
        this.sendOnError = sendOnError;
        this.sendOnFailure = sendOnFailure;
        this.sendOnSuccess = sendOnSuccess;
        this.sendOnWarning = sendOnWarning;
        this.address = address;
        this.configuration = configuration;
        this.locations = locations;
    }
}
