// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * Specifies the organization that produces this project.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Organization
{
    private String name;
    private String url;
    private java.util.Map<Object, InputLocation> locations;

    public Organization( String name, String url, Map<Object, InputLocation> locations )
    {
        this.name = name;
        this.url = url;
        this.locations = locations;
    }
}
