// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * Section for management of default plugin information for use in
 * a group of POMs.
 *       
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class PluginManagement
    extends PluginContainer
{

    public PluginManagement( List<Plugin> plugins, Map<Object, InputLocation> locations )
    {
        super( plugins, locations );
    }
}
