// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * 
 *         
 *         The <code>&lt;plugin&gt;</code> element contains
 * informations required for a plugin.
 *         
 *       
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Plugin
    extends ConfigurationContainer
{
    private String groupId;
    private String artifactId;
    private String version;
    private String extensions;
    private java.util.List<PluginExecution> executions;
    private java.util.List<Dependency> dependencies;
    private Object goals;

    public Plugin( String inherited, Object configuration, Map<Object, InputLocation> locations, String groupId,
                   String artifactId, String version, String extensions, List<PluginExecution> executions,
                   List<Dependency> dependencies, Object goals )
    {
        super( inherited, configuration, locations );
        this.groupId = groupId;
        this.artifactId = artifactId;
        this.version = version;
        this.extensions = extensions;
        this.executions = executions;
        this.dependencies = dependencies;
        this.goals = goals;
    }
}
