// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * 
 *         
 *         The <code>&lt;execution&gt;</code> element contains
 * informations required for the
 *         execution of a plugin.
 *         
 *       
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class PluginExecution
    extends ConfigurationContainer
{

    public final String id;
    public final  String phase;
    public final java.util.List<String> goals;

    public PluginExecution( String inherited, Object configuration, Map<Object, InputLocation> locations, String id,
                            String phase, List<String> goals )
    {
        super( inherited, configuration, locations );
        this.id = id;
        this.phase = phase;
        this.goals = goals;
    }

    @Override
    public boolean equals( Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        if ( !super.equals( o ) )
        {
            return false;
        }

        PluginExecution that = (PluginExecution) o;

        if ( goals != null ? !goals.equals( that.goals ) : that.goals != null )
        {
            return false;
        }
        if ( id != null ? !id.equals( that.id ) : that.id != null )
        {
            return false;
        }
        if ( phase != null ? !phase.equals( that.phase ) : that.phase != null )
        {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int result = super.hashCode();
        result = 31 * result + ( id != null ? id.hashCode() : 0 );
        result = 31 * result + ( phase != null ? phase.hashCode() : 0 );
        result = 31 * result + ( goals != null ? goals.hashCode() : 0 );
        return result;
    }
}
