// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * Contains the plugins management informations for the project.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class PluginConfiguration
    extends PluginContainer
{

    private PluginManagement pluginManagement;

    public PluginConfiguration( List<Plugin> plugins, Map<Object, InputLocation> locations,
                                PluginManagement pluginManagement )
    {
        super( plugins, locations );
        this.pluginManagement = pluginManagement;
    }
}
