// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * Describes the prerequisites a project can have.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Prerequisites
{
   private String maven = "2.0";
    private java.util.Map<Object, InputLocation> locations;

    public Prerequisites( String maven, Map<Object, InputLocation> locations )
    {
        this.maven = maven;
        this.locations = locations;
    }
}
