// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import org.codehaus.plexus.util.xml.Xpp3Dom;

import java.util.List;
import java.util.Map;
import java.util.Properties;

public class Profile
    extends ModelBase
{
    public final String id;
    public final  Activation activation;
    public final BuildBase build;

    public Profile( List<String> modules, DistributionManagement distributionManagement, Properties properties,
                    DependencyManagement dependencyManagement, List<Dependency> dependencies,
                    List<Repository> repositories, List<Repository> pluginRepositories, Xpp3Dom reports,
                    Reporting reporting, Map<Object, InputLocation> locations, String id, Activation activation,
                    BuildBase build )
    {
        super( modules, distributionManagement, properties, dependencyManagement, dependencies, repositories,
               pluginRepositories, reports, reporting, locations );
        this.id = id;
        this.activation = activation;
        this.build = build;
    }
}
