// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * Describes where an artifact has moved to. If any of the values
 * are omitted, it is
 *         assumed to be the same as it was before.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Relocation
{
    private String groupId;
    private String artifactId;
    private String version;
    private String message;
    private java.util.Map<Object, InputLocation> locations;

    public Relocation( String groupId, String artifactId, String version, String message,
                       Map<Object, InputLocation> locations )
    {
        this.groupId = groupId;
        this.artifactId = artifactId;
        this.version = version;
        this.message = message;
        this.locations = locations;
    }
}
