// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * Represents a set of reports and configuration to be used to
 * generate them.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class ReportSet
    extends ConfigurationContainer
{
    public final String id;
    public final List<String> reports;

    public ReportSet( String inherited, Object configuration, Map<Object, InputLocation> locations, String id,
                      List<String> reports )
    {
        super( inherited, configuration, locations );
        this.id = id;
        this.reports = reports;
    }
}
