// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

/**
 * A repository contains the information needed for establishing
 * connections with
 *         remote repository.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Repository
    extends RepositoryBase
{

    public final RepositoryPolicy releases;
    public final RepositoryPolicy snapshots;

    public Repository( String id, String name, String url, String layout, Map<Object, InputLocation> locations,
                       RepositoryPolicy releases, RepositoryPolicy snapshots )
    {
        super( id, name, url, layout, locations );
        this.releases = releases;
        this.snapshots = snapshots;
    }
}
