// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * Section for management of reports and their configuration.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Reporting
{
    private String excludeDefaults;
    private String outputDirectory;
    private java.util.List<ReportPlugin> plugins;
    private java.util.Map<Object, InputLocation> locations;

    public Reporting( String excludeDefaults, String outputDirectory, List<ReportPlugin> plugins,
                      Map<Object, InputLocation> locations )
    {
        this.excludeDefaults = excludeDefaults;
        this.outputDirectory = outputDirectory;
        this.plugins = plugins;
        this.locations = locations;
    }
}
