// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * 
 *         
 *         The <code>&lt;plugin&gt;</code> element contains
 * informations required for a report plugin.
 *         
 *       
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class ReportPlugin
    extends ConfigurationContainer
{
    public final String groupId;
    public final String artifactId;
    public final String version;
    public final java.util.List<ReportSet> reportSets;

    public ReportPlugin( String inherited, Object configuration, Map<Object, InputLocation> locations, String groupId,
                         String artifactId, String version, List<ReportSet> reportSets )
    {
        super( inherited, configuration, locations );
        this.groupId = groupId;
        this.artifactId = artifactId;
        this.version = version;
        this.reportSets = reportSets;
    }
}
