// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.List;
import java.util.Map;

/**
 * This element describes all of the classpath resources associated
 * with a project
 *         or unit tests.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Resource
    extends FileSet
{
    public final String targetPath;
    public final String filtering;

    public Resource( List<String> includes, List<String> excludes, Map<Object, InputLocation> locations,
                     String directory, String targetPath, String filtering )
    {
        super( includes, excludes, locations, directory );
        this.targetPath = targetPath;
        this.filtering = filtering;
    }
}
