// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.1,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model.immutable;

import java.util.Map;

public class Site
{
    public final String id;
    public final String name;
    public final String url;
    public final java.util.Map<Object, InputLocation> locations;

    public Site( String id, String name, String url, Map<Object, InputLocation> locations )
    {
        this.id = id;
        this.name = name;
        this.url = url;
        this.locations = locations;
    }
}
